version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: bellukstudio
      POSTGRES_PASSWORD: BellukStudio121.
      POSTGRES_DB: bellukstudioserver
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest-network

  myapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapi-app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 3005:3005  
    volumes:
      - .:/app
    networks:
      - nest-network

  # phpmyadmin tidak digunakan untuk PostgreSQL
  # Gunakan adminer sebagai alternatif:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - nest-network

volumes:
  postgres_data:

networks:
  nest-network:
    driver: bridge
