version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: BellukStudio121.
      MYSQL_DATABASE: bellukstudioserver
    ports:
      - 3306:3306  
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nest-network 

  myapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapi-app
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - 3005:3005  
    volumes:
      - .:/app
    networks:
      - nest-network

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: BellukStudio121.
    depends_on:
      - mysql
    networks:
      - nest-network         

volumes:
  mysql_data:  

networks:
  nest-network:
    driver: bridge
